a = 10;
b = [a];
c = [1, 2, 3];
print(a);
print("Hola");
print(c);
print((1 > 2 ? "Mun" + "do" : "a todos") + "!");
d = length(b);
length("IDLE");
print(length(c) + 5);
capitalizar("-");
e = length(capitalizar("MAYUSCULAS"));
print(capitalizar("m" + "M"));
colineales(b, c);
print(capitalizar(colineales(b, c) ? "B" : "C"));
multiplicacionEscalar(b, a);
print(length([1, length(multiplicacionEscalar(b, a, colineales(c, c))), length(capitalizar("2"))]));
